python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run01 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run02 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run03 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run04 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run05 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run06 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run07 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run08 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run09 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run10 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run11 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run12 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run13 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run14 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run15 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run16 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run17 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run18 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run19 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run20 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run21 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run22 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run23 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run24 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run25 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run26 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run27 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run28 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run29 --N 1
python3 ./cifar10_conv_np_hyperparam.py --dfa 1 --feedbacklearning 0 --gpu 2 --name cifar10_conv_np_nofeedback_run30 --N 1